lab_root: /opt/dns-lab
data_dir: /var/lib/dns-lab
zone: corp.test.
portal_name: portal.corp.test.
files_name: files.corp.test.
dns_ip: 10.60.20.53
portal_ip: 10.60.20.10
files_ip: 10.60.20.20
rogue_ip: 10.60.40.10
dns_api: http://10.60.20.53:9090
client_api: http://10.60.30.10:9090
attacker_api: http://10.60.40.10:9090
admin_api: http://10.60.10.10:8080
student_user: analyst
student_password: Analyst-DNS-2026!
student_password_hash: $6$vOBQlr62hXCK4PBQ$O.b9Z97.b.arTcTisIkYHFInnDY8bndhCiEKFZ6yTTBIEmE84.aqkLkkMFUH8K51I3ptsz2wVCu4hcFvYP4TG/
agent_token: 5j2BMSVCXtiJFeXDKyGWRjgOniEM_jeiI0v2LHS71wc
instructor_token: qtuMy_NMpKs3dpKIDqX156gEAKieFMP_Lh01S8NAY5o
legacy_secret: zr3dk3YgET4VDvXcM0q3tM08jTx5CSgDE77tI/gSEC8=
recovery_secret: OK0EBiuuHs7Iz9XwrpPaLQILoo3Hq8RzwRjKz/b643o=
bind_service: named
completion_flag: CRCZ{DNS_RESTORED_LEGACY_UPDATE_REVOKED}
